version: '3'
services:
  mysql:
    hostname: mysql-water-recycling
    container_name: mysql-water-recycling
    build:
      context: ./database
      args:
          - MYSQL_DATABASE=${MYSQL_DATABASE}
          - MYSQL_USER=${MYSQL_USER}
          - MYSQL_PASSWORD=${MYSQL_PASSWORD}
          - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db-data-water-2:/var/lib/mysql
  water-recycling:
    image: water-recycling
    build:  
      context: ./dotnet-backend
      dockerfile: Dockerfile
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - "8000:80"

volumes:
  db-data-water-2: